apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-08-22T16:47:35Z
  labels:
    app: userapp
    tier: frontend
  name: userapp
  namespace: default
  resourceVersion: "113062"
  selfLink: /api/v1/namespaces/default/services/userapp
  uid: 8b31dea8-c4fc-11e9-92e4-42010a8a0230
spec:
  clusterIP: 10.11.240.222
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30586
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: userapp
    tier: frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.247.91.115
