apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-08-22T22:32:12Z
  generation: 1
  labels:
    app: backend
    tier: backend
  name: dataservice
  namespace: default
  resourceVersion: "173988"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/dataservice
  uid: af70eb35-c52c-11e9-92e4-42010a8a0230
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backend
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
        tier: backend
    spec:
      containers:
      - image: gcr.io/ultra-bearing-231304/backend:latest
        imagePullPolicy: Always
        name: dataservice
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-08-22T22:32:15Z
    lastUpdateTime: 2019-08-22T22:32:15Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-08-22T22:32:12Z
    lastUpdateTime: 2019-08-22T22:32:15Z
    message: ReplicaSet "dataservice-6f75b49d86" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
