apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
      dataservice'
  creationTimestamp: 2019-08-22T22:32:12Z
  generateName: dataservice-6f75b49d86-
  labels:
    app: backend
    pod-template-hash: 6f75b49d86
    tier: backend
  name: dataservice-6f75b49d86-ksx6w
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: dataservice-6f75b49d86
    uid: af72ac2b-c52c-11e9-92e4-42010a8a0230
  resourceVersion: "173986"
  selfLink: /api/v1/namespaces/default/pods/dataservice-6f75b49d86-ksx6w
  uid: af769b53-c52c-11e9-92e4-42010a8a0230
spec:
  containers:
  - image: gcr.io/ultra-bearing-231304/backend:latest
    imagePullPolicy: Always
    name: dataservice
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      requests:
        cpu: 100m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-zz2vz
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: gke-k8s-medium-default-pool-ea353ee0-7kwn
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-zz2vz
    secret:
      defaultMode: 420
      secretName: default-token-zz2vz
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-08-22T22:32:12Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-08-22T22:32:15Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2019-08-22T22:32:15Z
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2019-08-22T22:32:12Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://fd1f4904f9452b4b686df1fceebce62e8bc227f6d15b1512f4196b511cc7a01b
    image: gcr.io/ultra-bearing-231304/backend:latest
    imageID: docker-pullable://gcr.io/ultra-bearing-231304/backend@sha256:66b9a3b217d3c84d89194140c22f3f63036333f47b765945d8deaef56dce7b0c
    lastState: {}
    name: dataservice
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2019-08-22T22:32:15Z
  hostIP: 10.138.0.12
  phase: Running
  podIP: 10.8.2.11
  qosClass: Burstable
  startTime: 2019-08-22T22:32:12Z
