apiVersion: v1
data:
  secret_key.txt: U0VDUkVUX0tFWQo=
  secret_value.txt: VGhpc0lzTXlTZWNyZXQxMjM0NQo=
kind: Secret
metadata:
  creationTimestamp: 2019-08-23T06:15:14Z
  name: my-app-secret
  namespace: default
  resourceVersion: "255131"
  selfLink: /api/v1/namespaces/default/secrets/my-app-secret
  uid: 5eb3ce0e-c56d-11e9-82c8-42010a8a0202
type: Opaque
