apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-08-22T22:32:54Z
  generation: 1
  labels:
    app: frontend
    tier: backend
  name: userapp
  namespace: default
  resourceVersion: "174129"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/userapp
  uid: c83ad51f-c52c-11e9-92e4-42010a8a0230
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
        tier: backend
    spec:
      containers:
      - image: gcr.io/ultra-bearing-231304/userapp:latest
        imagePullPolicy: Always
        name: userapp
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-08-22T22:32:56Z
    lastUpdateTime: 2019-08-22T22:32:56Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-08-22T22:32:54Z
    lastUpdateTime: 2019-08-22T22:32:56Z
    message: ReplicaSet "userapp-6d9f99c49" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
