apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
    tier: backend
  name: dataservice
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend
    tier: backend
  type: ClusterIP
status:
  loadBalancer: {}
