apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: frontend
    tier: backend
  name: userapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      tier: backend
  template:
    metadata:
      labels:
        app: frontend
        tier: backend
    spec:
      containers:
      - image: gcr.io/ultra-bearing-231304/userapp:latest
        name: userapp
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: APP_NAME
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: my-app-secret
              key: SECRET_KEY
