apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
    tier: backend
  name: userapp
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31792
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
    tier: backend
  type: LoadBalancer
